ALTER TABLE players ADD `stat_str` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE players ADD `stat_int` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE players ADD `stat_dex` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE players ADD `stat_vit` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE players ADD `stat_spr` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE players ADD `stat_wis` TINYINT UNSIGNED DEFAULT 0;